name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}
jobs:
  release:
    permissions:
      contents: write  #  to create release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write  #  to create pull request (changesets/action)

    if: github.repository == 'devessier/xstate-report'

    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            npm run preview &

            until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
              printf '.'
              sleep 5
            done

            echo 'Server is listening'

            node ./build-report.js --production

            git add .
            git commit -m "chore: generate report"
            git push

          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
